#!/usr/bin/env python3
"""Set the shared bootloader/application PUF build configuration."""

import argparse
from pathlib import Path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--region", type=int, required=True, choices=range(5))
    parser.add_argument("--debug-capture", choices=("on", "off"), required=True)
    args = parser.parse_args()
    path = Path("common/puf_build_config.h")
    path.write_text(
        "/* Generated by configure_puf.py. */\n#pragma once\n\n"
        f"#define LPOFI_PUF_SOURCE_REGION {args.region}\n"
        f"#define LPOFI_PUF_DEBUG_CAPTURE {1 if args.debug_capture == 'on' else 0}\n",
        encoding="utf-8",
    )
    print(f"Configured source region {args.region}; raw UART capture is {args.debug_capture}.")


if __name__ == "__main__":
    main()
